spring:
  application:
    name: hello-spring-cloud-netflix-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8181

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

zuul:
  routes:
    api-consumer-feign:
      path: /api/consumer/feign/**
      serviceId: hello-spring-cloud-netflix-consumer-feign
    api-consumer-ribbon:
      path: /api/consumer/ribbon/**
      serviceId: hello-spring-cloud-netflix-consumer-ribbon