version: '3'
services:
  itoken-eureka-1:
    restart: always
    image: 192.168.0.111:9090/itoken/itoken-eureka
    container_name: itoken-eureka-1
    ports:
      - "8761:8761"
    networks:
      - itoken-eureka-1-network

  itoken-eureka-2:
    restart: always
    image: 192.168.0.111:9090/itoken/itoken-eureka
    container_name: itoken-eureka-2
    ports:
      - "8861:8761"
    networks:
      - itoken-eureka-2-network

  itoken-eureka-3:
    restart: always
    image: 192.168.0.111:9090/itoken/itoken-eureka
    container_name: itoken-eureka-3
    ports:
      - "8961:8761"
    networks:
      - itoken-eureka-3-network

networks:
  itoken-eureka-1-network:
  itoken-eureka-2-network:
  itoken-eureka-3-network:
