spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hello-spring-cloud-zipkin


server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false