spring:
  cloud:
    config:
      # 配置服务中心的地址
      uri: http://localhost:8888
      # 配置文件名称的前缀
      name: consumer-feign
      # 配置仓库的分支
      label: master
      # 配置文件的环境标识（dev，test，prod）
      profile: dev