spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://192.168.0.112:8084

server:
  port: 9411

eureka:
  instance:
    hostname: 192.168.0.112
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8861/eureka/,http://${eureka.instance.hostname}:8961/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info