spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.0.111:8080/itoken/itoken-config.git
          search-paths: respo
          username: wenwl
          password: 12345678
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info