spring:
  application:
    name: hello-spring-cloud-netflix-consumer-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8764

eureka:
  instance:
    hostname: localhost
    # 增加用于集群的配置，集群名为 consumer-ribbon，与 Turbine 的配置匹配
    metadata-map:
      cluster: consumer-ribbon
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/