spring:
  application:
    name: itoken-service-redis
  redis:
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
    sentinel:
      master: mymaster
      nodes: 192.168.0.111:26379,192.168.0.111:26380,192.168.0.111:26381

server:
  port: 8502