spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 是否注册到Eureka， 集群需要开启
    registerWithEureka: true
    # 是否从Eureka获取注册信息，同步其他Eureka节点，集群需要开启
    fetchRegistry: true
  server:
    # 关闭自我保护模式
    nable-self-preservation: false
    # 清理服务间隔4s，默认 60*10000
    eviction-interval-timer-in-ms: 4000