spring:
  application:
    name: itoken-web-admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html


server:
  port: 8601

feign:
  hystrix:
    enabled: true