spring:
  application:
    name: itoken-service-admin
  zipkin:
    base-url: http://192.168.0.112:9411
  boot:
    admin:
      client:
        url: http://192.168.0.112:8084
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html


server:
  port: 8601

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.112:8761/eureka/,http://192.168.0.112:8861/eureka/,http://192.168.0.112:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info