version: '3'
services:
  itoken-zipkin:
    restart: always
    image: 192.168.0.111:9090/itoken/itoken-zipkin
    container_name: itoken-zipkin
    ports:
      - "9411:9411"
    networks:
      - itoken-zipkin

networks:
  itoken-zipkin: