spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/your-addr/spring-cloud-config
          search-paths: respo
          username: root
          password: 12345678
  zipkin:
    base-url: http://localhost:9411
    
server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/